language: android
before_script: cd scripts
android:
  components:
  - android-23
  - build-tools-23.0.0
  - doc
  - extra-android-support
  - extra-android-m2repository
script: ./build_release_bundle.sh
env:
  secure: "bMpgqdDmk+R8P3XQi6yZxEhyM6O88aAJffgFDaTUMKmxXv5cWNSt48fQX/LOKyRb28gnduZVJHznM1c06+lQPcb3It3iEsdAPNx5VwT5FUqpb9GkDBoGrPyith4rB7eVe8d62VDHKBSSctW6yhw7NCrimlWX90jK996k4u7X2X8hUi4bGvatGxQnfZXgRk14AjTIbQyFYjAKWhtuMlYf7UxisXjKoofXiJPPHrA7UYQNjlzIw+/nWCv5HHDNfxqy1uktT71Kq4vzbVXR6f6rMmE5p0sy4Irh1R72UqwbKx08o1BeBG2JoZJNapCf79ES4D+QyMus279123whUI8OAaBhIAPryH3kwQEWbm8KBV0/vIU/iOvIVb1RtGZKeHZriOB1tDON2nFhGW4SJUN3Xc5JYmptxlU0RyRco7TdKCvR8MMW6URPzXXXurbdQ9CX1EsNX7c+wxtnBIr2fwPeK+UZStdDFhdnswmLWlzp2W/O2BOuax8CE1XWvRmgA2SEsFZb4VGb2KVUItHpxG5Ncc+lwTqxz16bT+XWULKb7k8FBtvpQbIsgItdxHBskuV6b89PmSHMDdAXOgFu5NECw9sOxW6lUenqiF41kaHk7JEuFpOgoto/LAMfambQb/PvWxUYXbDvnJpQ2J6QE1oXhnsiF4NMUXmjxE6Vn6r4HP8="
  secure: "S9srcH/Ffw+2gWxw+Gw3rRR77KFdBN0w0Il9K9snt+pN4B+mVi2QOa30hhVMNgRB5iZ3QmjtxBkh0GA8zJvolXEtYG4J3SIyU1yP1KOABOzSdg/JJyYX6c0cnJy1JYP+Y0hmUW31ZqTXV0MdWqRBf6FCOgNWv9GT7I0EOZqf/kLHV6PHHhNt370dWYz5bsLtIIv2EHHek4r9khIyj4PNIS86tN8v1wsGs1rnlyD5cS8onOsP8n8NMsbXmwAckzKlC//GZIE+IooLjQajlyb49BbwT2VhYnCr0uWETGqjuj6Ls9/1vlRTsOiiZP2yO22ddOjRjEY6C8paGQJxVXggppRxSn7ITbZQkWO8inzJE8mWvuIXknRGECeDC0dfuF0/W+7jcZPw14rKLiJk4PBeOzV5clVLNk1u6EsWEmWfiCuqnIjuctMFjBMk5jZIHtDMBQW7dFTNcLS5F7cpubuJ8PC871TCO/K0B6depX6tMUG2Oi2ypLulP6gcQyVX6XsVCq67Hbdi66Ul6OEm9E78pywfZamkcR+W1azWirvszpDN4SSIb9zx8/3U6K1bU7C+M0fxh3HncsCvvTX09p8fmruIdtXy2/LY+uML3ypwFwYTQchXBhU3LFed7tLXH3R0PojbxwKoP6r23uyhmeQuf7cU/ughi+CQXn7m15xM2ZI="
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
jdk:
  - oraclejdk8