language: android
before_script: cd scripts
android:
  components:
  - android-23
  - build-tools-23.0.0
  - doc
  - extra-android-support
  - extra-android-m2repository
script: ./build_release_bundle.sh
env:
  secure: "wkMlone+SV+2fw7Kqa9HDtSTa0yf7oCEPHIA3xSlJ6GD223AIejfD5Hr8vH11902fswQl7DkfYGII/39hVv+uFakSWT8ZzLm06uYb7oSU5zMeDQ11/dv+8CW19cZD8X5PYGx3x3NnPfDk9aySRlpsav8+FGKRtqxAn1wo25LcjBhCQcRsjSkEva+E67GDbEhKpCkyVCFNOx8ajD2ldswKwMzW+WNQnHaM42xrmLeeqFLq6Zwqj7PIglKZhsXQ9KejKhnHMmwAcRx+SErLPExOrY6ZMb5SfJ3XvpmjLqicr4fpwB1hrPKrBSELLgR6II9b8wzWNay0ugVFD65z3Ne1pe+2wTn99gbrv1tzG9zW8AQweTz06i7hdavazj44CaLNw9Vryo7SsQ18e7Oz8jL1yqgtu/VW5LsBeUK4VxDwkY8VpoxGcmtokLL3LRu94k+M7/yCDi/Nzu7b85MlhHA4V4qtUILU7ATZ9Rv8OrAHFtoeqgxidRvmZsRFCcr9SbXeVQKveFWfCcaKv9m5i8KonFnmI9RoYZ0h5XgbBP6/WxHDpVK4vdf/KLVqd1xhgduVymWrHQK1fqmp1oTdX+e8P09X14XbbvMIAQXSGXBw9dx9FSjkqzpmH5rQc6sX0E5xK9M+ATrLw8nFXvKCYxMGEVyii5QUJin8ud7m6+yTxo="
  secure: "S9srcH/Ffw+2gWxw+Gw3rRR77KFdBN0w0Il9K9snt+pN4B+mVi2QOa30hhVMNgRB5iZ3QmjtxBkh0GA8zJvolXEtYG4J3SIyU1yP1KOABOzSdg/JJyYX6c0cnJy1JYP+Y0hmUW31ZqTXV0MdWqRBf6FCOgNWv9GT7I0EOZqf/kLHV6PHHhNt370dWYz5bsLtIIv2EHHek4r9khIyj4PNIS86tN8v1wsGs1rnlyD5cS8onOsP8n8NMsbXmwAckzKlC//GZIE+IooLjQajlyb49BbwT2VhYnCr0uWETGqjuj6Ls9/1vlRTsOiiZP2yO22ddOjRjEY6C8paGQJxVXggppRxSn7ITbZQkWO8inzJE8mWvuIXknRGECeDC0dfuF0/W+7jcZPw14rKLiJk4PBeOzV5clVLNk1u6EsWEmWfiCuqnIjuctMFjBMk5jZIHtDMBQW7dFTNcLS5F7cpubuJ8PC871TCO/K0B6depX6tMUG2Oi2ypLulP6gcQyVX6XsVCq67Hbdi66Ul6OEm9E78pywfZamkcR+W1azWirvszpDN4SSIb9zx8/3U6K1bU7C+M0fxh3HncsCvvTX09p8fmruIdtXy2/LY+uML3ypwFwYTQchXBhU3LFed7tLXH3R0PojbxwKoP6r23uyhmeQuf7cU/ughi+CQXn7m15xM2ZI="
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
jdk:
  - oraclejdk8