language: android
before_script: cd scripts
android:
  components:
  - android-23
  - build-tools-23.0.0
  - extra-android-support
  - extra-android-m2repository
script: ./build_release_bundle.sh
secure: FeL0TccPB1ixZabgFGJ9u/LxnQ3mOX3jwVMfBfugXuEnbc67aOUor68GAW7JOx9eRFkHuUWreIijLjhWv6gUiWu45+gKQkW6m46hHnDKl01tNnC9YfZd8wAE9XLrA9Hv10gt7h7Q7fXF+Kf9cn8ptzC86CMhhP65wDf+ho+/VVSxVLphiVJzrxEobKam14fAgx94riZhRGns2FmCEa3TW1UbOfvuGs2YsYvtMlI3GqoF1B5vMkCUMNe9l4uZh8S4ADBNVEHwHbDQRwyW33gOYSB1qNr5uZbqbBr3VIcHoLMHeu+FHF+EdzhwqE9qLQYT4zTYJAP4vKwvLOL35hV1+r/dSi0L25NGPJcF8HYhy5u+mqRAKEhpC2PC3Cxh+YzVj19Q9S+WkBK94SsB2qc7ZvNWQGS+Bpu8cs/864yLByWgM5SeKNJB7+npAWVbjRVIhu3/WHZS0lOI7bKnfuo00LU82aqE5Px9/OE7OmJNFRrrHpkK8nfNj32B0WXPnHvApVmm801CTl+Cqpnb6Yvwa7BOQlAtw8wpCrzlUJYo9OauTiA5BingYod/z8fD7BjxwP7faORngXTo4e08pdgRB96U/K+bXK9VXKY9cISqLZEmv+S1BG9dNiENaCUpcs9rK7HmDV/qqxBjH1kH+EgczMSpDVB4cRkbj6HYHM3ujp0=
secure: aAjF2Iv4lqavqO5Kq45vuqJBu3t/bTb3rSmX8QqT9430xnu8ZbwVx2T/p5UQjmfpCW9f4xtmvF/460nnzMz5VwSOAktolC1fL+CdVhpilCB29xXdq7Paf2HI2abKDDLr/SeJFpOYw0YnL6x+gaQqtmNTjG059/HKBWTMO6ppeBvevMw7trw+kq0YKDpCEJIYinoFr0QnNxiMSxyUpD3Aasp+iT24gOFh0sk2Vh7Oai9guEeil19mcbirTFOlNSvRSA2QGgU+zhPKpaCu9Fkd0XUhO90lrDUlJYBxOOkX31wum5uvrgrpWJxGcNjrtjmkYb2fZGEcWT0ZxdghYmcBrdxgmoAOw3y7D37JrNYgOSXhJ+2bwn3zD6qfkvTdhgXB2qbri1l7mwKZKXzPeR13+AqqNB8iGDx2diSFgVFvj8LPFSOjSBrMJeCVliMyZrnI11FfEkBBt+dZnQSwmj21Xh345km98Ecpcefd6jP6X6GWwqwuZn1eiHkm9qLryaH4iFkDyCg/6K3T3kjdA2EhpqtSzmslTet2KwOgwdb6pApgLr9bkPxP2mINliZfBlwWXHL9bH0G6M4CmIcidqxRs3OEMVN62pHioEqEdlM3RWSD9Je4d3V3qNThmIHLLL4fikQAnVENXnDuSINrMEPziAwCMtr9QyN4GB69XVdYOjw=
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
jdk:
  - oraclejdk8